dist: trusty
language: bash
script:
  - cd po
  - make *.po
  - make

env:
  global:
    # encrypted github token used to deploy
    - secure: >-
        xlAWGNFLkDRbYN5MGpA7cVAesuwa0EdfiMZEfOGktwm8hSzqmKkaoF6fActJPv0lukU40pMaE6zTe6v8QPHNlV4MyQDKotSd3FU1Bth7g/oNlJ3SNwMT03dwASRIsBM1WwyiRHAZpvlogmxABN0kjB+2ZeD6aTIVW8tGZehBUQcsysJbQPpuyjwMOvtk0R6aOOuw7sPEF03ohmXsLWZsTTMAtFWrXqOvKxSxkBEEZdhe7Er3Nf+Ef77F5CUDdfPeqQ7itak2QrYuFyZoBqFsMi7vI3emh0nljtSKkpoYQCk7GNAyAoC9X8y2qCSQV33Wz+UXp83WpEyqll1H6/4BqNrDnm8ZCT64WXHv911nkn/0y/oRwxq+wumTkcU6a1AYYukf07/8z4ZfSNIT3m2g/wNAYq2VIs9Ay27aB23ZQUvcsdhSsGNvDjrAYRoLJUEzSqj8WnY8qr+ZpCWhWKZAe202JTquYEPwSkj1EFMFS/D6Rf8V3M4z0KZrnD6rceWnsAbZiWfp8APqbqTuZYMantaEMkix5C+6wGsSchXgjfSabvkicjVnFq4G3XEyrpDiMjrBo9gxePsKLpxzCNuA+4XjmhsB3IHSrqmnqqxn0eLkDZIrjeUfVocd1XbBlw0JCMDF3dqZsKhg/zSg8ID891p1XhpHbpweBi5PAu8SdtE=
    - GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/Jungle-Bus/transport_mapcss.git

deploy:
  provider: script
  skip_cleanup: true
  script:
    - cd .. && ./deploy.sh

  on:
    branch: ci
